config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'top#index'
  get '/measure' => 'heart_beats#measure'
  get '/heart_beats/graph'
  get '/calories' => 'top#calories'
  get '/ranking' => 'top#ranking'
  resources :heart_beats, :only => [:index, :create]

end

app/models/heart_beat.rb
class HeartBeat < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :heart_beats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # accept null
  protect_from_forgery with: :null_session
end

app/controllers/heart_beats_controller.rb
class HeartBeatsController < ApplicationController
  # before_action :check_api_key

  def measure
  end
  def graph
    beats_data = User.first.heart_beats.limit(200).order(id: :desc)
    time  = beats_data.pluck(:beat_date_time).map {|time| time.strftime('%H:%M:%S')}.reverse
    null_times = Array.new(198, "")
    times = [time.first, null_times.flatten, time.last]
    beats = beats_data.pluck(:heart_beat).reverse
    @all_calories = 0
    calories = beats.map do |beat|
      @all_calories += beat.to_f/ (220-34) * 40 * 1 / 12 * 62 / 1000 * 5
    end
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '心拍数/34歳/174cm/62kg/男性')
      f.xAxis(categories: times.flatten)
      f.options[:yAxis] = [{ title: { text: '心拍数' }}, { title: { text: '消費カロリー'}, opposite: true}]
      f.series(name: '消費カロリー',     data: calories, type: 'column', yAxis: 1)
      f.series(name: '心拍', data: beats, type: 'spline')
    end
  end


  def index
    User.first.heart_beats.create(beat_date_time: Time.now, heart_beat: params[:heart_beat])
    puts "create!!"
    render nothing: true
  end

  private
  def heart_beat_params
    params.require(:heart_beat).permit(:heart_beat)
  end

  # api keyのチェック
  def check_api_key
    if request.headers['api-key'] == "test_key"
      puts "accept"
      return true
    else
      puts "not accept"
      render json: {message: "api-key error"}.to_json, status:400
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heart_beats_helper.rb
module HeartBeatsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/heart_beats/graph.html.slim
= high_chart("sample", @graph)

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : "MiyaZap"
    = favicon_link_tag
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to image_tag('miyazap.jpg', { :width => '100', :height => '47', :alt => 'Miyazap'}), root_path
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "Graph", heart_beats_graph_path
            li = link_to "Ranking", ranking_path
            li = link_to "Calories", calories_path
            li = link_to "Measure", measure_path
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
          /! /.well
        /! /span
      /! /row
      .footer
    /! /container

app/views/top/calories.html.erb
<%= stylesheet_link_tag "miyazaki1", :media => "all" %>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>
MIYAZAP
</title>
</head>
<body>

<h2>カロリー表示</h2>

<div style="border-style: solid ; width:90%; border-width: 2px;">
<h3 class="heading">今日の目標
<FONT size="8">
<Div Align="right">1000kcal
</Div>
</FONT>
</h3>
</div>

<br><br>

<div style="border-style: solid ; width:90%; border-width: 2px;">
<h3 class="heading">累計(3日目)
<FONT size="8">
<Div Align="right">2531kcal
</Div>
</FONT>
</h3>
</div>

<div style="text-align:right">

<div style="float:left">
	<br>
<a href="https://www.instagram.com"><%= image_tag("insta.png") %></a>
</div>

<div>
  <a href="/heart_beats/graph" class="button" style="text-decoration: none;">
<span>心拍数</span></a>
</div>

</div>
</body>
</html>

app/views/top/index.html.slim
= image_tag "miyazap.jpg" ,{ :width => "100%" }

app/views/top/ranking.html.erb
<link rel="stylesheet" type="text/css" href="miyazaki3.css">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>
MIYAZAP
</title>
</head>
<body>

<div class="ranking">
<FONT size="5">
<h2>今日のランキング</h2>
</FONT>

<ol>
<li class="rank1">1位 あきちゃん</li>
<li class="rank2">2位 ひろし</li>
<div style="background: #FFB6C1; width:100%; border: 1px solid #CC0000; height:100％; padding-left:1px; padding-right:1px; padding-top:10px; padding-bottom:10px;">
<li class="rank3">3位 まゆちゃん</li></div>
<li class="rank4">4位 めぐちゃん</li>
<li class="rank5">5位 ゆきりん</li>
</ol>

</div>

<div style="text-align:right">

<div style="float:left">
<a href="/calories" class="button" style="text-decoration: none;">
<FONT size="5">
<span>カロリー</span></FONT></a>
</div>

<div>
  <a href="/heart_beats/graph" class="button" style="text-decoration: none;">
  <FONT size="5">
<span>日別心拍数</span></FONT></a>
</div>


</body>
</html>